### ISSUE TITLE
disqus

### ISSUE THREAD

**Issue by GuyliannEngels** [yannkevinlowe/yannkevin-lowe-blog#2]
salut @yannkevinlowe,

tu dois impérativement ajouter disqus rapidement à ton blog

**Comment by yannkevinlowe** [comment]
Je comprends pas cest quoi ''disqus''?

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by yannkevinlowe** [comment]
Je vois ''disqus''

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by yannkevinlowe** [comment]
mais comment ajouter

**Comment by GuyliannEngels** [comment]
Disqus est l outil qui te permet d avoir un système de commentaire / discussion en dessous de tes articles. Tu peux retrouver un exemple de site avec disqus à l adresse <https://guyliann.github.io/guyliann-engels-blog/posts/2019-09-18-article-1/>

**Comment by GuyliannEngels** [comment]
Tu n'as toujours pas ajouté disqus, ne tarde plus
